version: "3.8"

services:
    # 1. Next.js サービス
    next-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        environment:
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - dynamodb
            - lambda

    # 2. DynamoDB サービス
    dynamodb:
        image: amazon/dynamodb-local:latest
        container_name: dynamodb
        ports:
            - "8000:8000"
        volumes:
            - dynamodb-data:/home/dynamodblocal/data
        command: "-jar DynamoDBLocal.jar -sharedDb"

    # 3. AWS Lambda サービス
    lambda:
        image: amazon/aws-lambda-nodejs:latest
        container_name: aws-lambda
        ports:
            - "9000:8080"
        volumes:
            - ./lambda:/var/task
        environment:
            - AWS_REGION=ap-northeast-1

volumes:
    dynamodb-data:
